extends Node

## S03 Luckius paper (CC0, opengameart.org/content/various-paper-sound-effects).
const PAPER = preload("res://audio/sfx/foley/paper_sheet.mp3")
## S01 Kenney impactPlate_heavy (CC0, kenney.nl/assets/impact-sounds).
const STAMP = preload("res://audio/sfx/foley/ink_stamp_cc0.ogg")
const LEVER = preload("res://audio/sfx/foley/route_lever.wav")
const LATCH = preload("res://audio/sfx/foley/door_latch.wav")
## S01 Kenney impactWood_medium (CC0): body weight meets the seat.
const CHAIR = preload("res://audio/sfx/foley/chair_settle_cc0.ogg")
const PAPER_TURN = preload("res://audio/sfx/foley/paper_turn.wav")
## Generated by tools/generate_action_foley.py (deterministic, project-owned).
const PEN = preload("res://audio/sfx/foley/pen_scratch.wav")
const KEY = preload("res://audio/sfx/foley/key_click.wav")
const HINGE = preload("res://audio/sfx/foley/door_hinge.wav")
const SLIDE = preload("res://audio/sfx/foley/sheet_slide.wav")
const WICK = preload("res://audio/sfx/foley/wick_turn.wav")

## Identical samples machine-gun; a small pitch spread reads as a hand.
const JITTER: float = 0.06

## Local, physical sounds sit on their own bus so the room's fader never has to
## choose between the wind and a hand closing on paper.
const FOLEY_BUS: StringName = &"Foley"

func _ready() -> void:
	_bind.call_deferred()

func _bind() -> void:
	var office := get_parent() as M1OfficeController
	var paper := AudioStreamPlayer.new()
	paper.name = "Paper"
	paper.stream = PAPER
	paper.volume_db = -20.0
	paper.bus = FOLEY_BUS
	add_child(paper)
	var paper_down := AudioStreamPlayer.new()
	paper_down.name = "PaperDown"
	paper_down.stream = PAPER_TURN
	paper_down.volume_db = -24.0
	paper_down.bus = FOLEY_BUS
	add_child(paper_down)
	office.document_viewer.document_opened.connect(func(_id): _play_varied(paper))
	office.document_viewer.document_closed.connect(func(_id): _play_varied(paper_down))
	# The new blank sheet landing on the writing zone has its own short
	# contact sound — the feed, not the viewer.
	var feed := AudioStreamPlayer.new()
	feed.name = "PaperFeed"
	feed.stream = PAPER
	feed.volume_db = -24.0
	feed.bus = FOLEY_BUS
	add_child(feed)
	var transcript := office.session_controller.transcript_paper
	transcript.sheet_fed.connect(func(): _play_varied(feed))
	var slide := _source("SheetSlide", SLIDE, transcript.global_position, -26.0)
	transcript.sheet_archived.connect(func(): _play_varied(slide))
	# The nib on paper: far under the sounder, so it never competes with Morse.
	var pen := _source("Pen", PEN, transcript.global_position, -30.0)
	if transcript.writer_rig != null:
		transcript.writer_rig.glyph_contact.connect(func(_i): _play_varied(pen))
	var key := office.session_controller.telegraph_key
	if key != null:
		var click := _source("KeyClick", KEY, key.global_position, -16.0)
		key.key_touched.connect(func(): _play_varied(click))
	var stamp := _source("Stamp", STAMP, office.copy_commit_desk.global_position, -13.0)
	# The stamp sound is the physical contact of the press, never the intent
	# a deadline may still reject (B1), and never the acceptance itself.
	office.copy_commit_desk.stamp_contact.connect(func(_id): stamp.play())
	# The hand takes the lever: the throw starts here, the stop lands on the board.
	var lever := _source("LeverThrow", LEVER, office.routing_board.global_position + Vector3(0, 0.7, 0), -20.0)
	office.routing_board.routing_action_selected.connect(func(_a): _play_varied(lever))
	var lamp_life := office.get_node_or_null("LampLife") as LampLife
	if lamp_life != null:
		var wick := _source("Wick", WICK, office.get_node("DeskSetup/OilLamp").global_position, -20.0)
		lamp_life.wick_turned_up.connect(wick.play.bind(0.0))
		lamp_life.wick_turned_down.connect(wick.play.bind(0.0))
	var register := office.get_node_or_null("TelegraphSessionController/TapeRegister") as TapeRegisterController
	if register != null:
		var winder := _source("RegisterWind", WICK, register.global_position, -18.0)
		register.register_wound.connect(func(): _play_varied(winder))
	var latch := _source("Latch", LATCH, Vector3(-1.6, 1.0, 2.25), -15.0)
	office.office_door.door_rattled.connect(latch.play.bind(0.0))
	office.office_door.door_opened.connect(latch.play.bind(0.0))
	var hinge := _source("Hinge", HINGE, Vector3(-2.05, 1.2, 2.3), -17.0)
	office.office_door.door_opened.connect(hinge.play.bind(0.0))
	var chair := _source("Chair", CHAIR, office.get_node("Chair").global_position, -22.0)
	office.operator_seat.seated.connect(func():
		chair.pitch_scale = 1.0
		chair.play())
	# Standing drags the chair back: lower, heavier than the sit.
	office.operator_seat.stood.connect(func():
		chair.pitch_scale = 0.8
		chair.play())

func _play_varied(player: Node) -> void:
	player.pitch_scale = 1.0 + randf_range(-JITTER, JITTER)
	player.play()

func _source(label: String, stream: AudioStream, position: Vector3, volume: float) -> AudioStreamPlayer3D:
	var player := AudioStreamPlayer3D.new()
	player.name = label
	player.stream = stream
	player.volume_db = volume
	player.unit_size = 2.0
	player.max_distance = 8.0
	player.bus = FOLEY_BUS
	add_child(player)
	player.global_position = position
	return player
